### ISSUE TITLE
Can't connect, invalid start byte

### ISSUE THREAD

**Issue by DWFlanagan** [liamhays/hpex#1]
Hi,

When I go to I/O... Start Server on the HP-48GX and try to connect from the GUI, the calculator sends 5 packets but I get the error

```bash
pi@raspberrypi:~/hpex $ python hpex.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/hpex/kermit_pubsub.py", line 118, in run
    self.line = self.proc.readline()
  File "/usr/local/lib/python3.9/dist-packages/ptyprocess/ptyprocess.py", line 834, in readline
    return self.decoder.decode(b, final=False)
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
```

I'm using Debian 11 (bullseye) on a Raspberry Pi 400.

Thanks!

**Comment by liamhays** [comment]
Make sure the calculator is in translate mode 3 (aka `Chr 128-255` in the Transfer menu, or `3 TRANSIO` in RPL). This has to be set manually before you use HPex, because when the UTF-8 decoder tries to process bytes greater than 0x7f (as used by special characters on the HP 48), it tries and fails to assemble a larger Unicode character. [More info on UTF-8 here.](https://en.wikipedia.org/wiki/UTF-8)

In mode 3, the calculator will replace special characters with escaped strings. The User Guide has a table of the escape sequence for each non-ASCII character.

By the way, you can start the server by pressing [right-shift][R].

**Comment by DWFlanagan** [comment]
Thanks, that worked! I was able to browse the variables on the calculator. When I tried to transfer the variable starting with sigma to my desktop I got an error ("Undefined name") but that might be more of an edge case.

Thanks for making this fantastic tool! I have never been able to transfer libraries onto my calculator before now.

**Comment by liamhays** [comment]
Alright, so on further investigation, using Kermit GET does not trigger the HP 48's character translation _for the variable name itself._ For example (and as far as I can tell, I might just be missing something), running "GET \GSA" will not actually tell the calculator to send a variable called 'ΣA'. The calculator instead responds with an "Invalid Name" error.

This seems to me like a flaw in the HP 48's Kermit server implementation. If that's really the issue, I'll add functionality to HPex to prevent or warn against transferring files with special characters in the name.
